### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by chrisben** [nerves-project/nerves_wpa_supplicant#6]
The line:
`{:ok, pid} = Nerves.WpaSupplicant.start_link("/var/run/wpa_supplicant/wlan0")`

fails because start_link expects at least 2 parameters here.

Should the correct line be something like:
`{:ok, pid} = Nerves.WpaSupplicant.start_link("wlan0", "/var/run/wpa_supplicant/")`

but this crashes..

**Comment by taiansu** [comment]
This works for me:
`{:ok, pid} = Nerves.WpaSupplicant.start_link("wlan0", "/var/run/wpa_supplicant/wlan0")`

after that I also got `Nerves.WpaSupplicant.request(pid, :PING)` worked, 
but then my rpi3 freezed at `Nerves.WpaSupplicant.scan(pid)`

**Comment by Tony1928** [comment]
bbgw wifi problem solved [here](https://github.com/nerves-project/nerves_system_bbb/issues/12)

but my rpi (whtih 8192cu wifi driver) freeze/lock up while doing **_Nerves.WpaSupplicant.scan(pid)_**, too, _**hello_wifi**_ example just do not work

besides, you might unlock it  by 
1) `<ctrl>+g`
2) i 2 (command interrupt, to go back working condition) 

more, you might verify some function in the shell
1) `<ctrl>+g`
2) s 'Elixir.Nerves.Runtime.Shell'
3) j (check where shell is)
4) c 2 (assume to be "2")
5) then you are there in shell mode of busybox
6) `<ctrl >+g` (any time go back to you "iex" mode (pleased noted: `<ctrll>+c <ctrl>+c` will shutdown device)

**Comment by ConnorRigby** [comment]
@Tony1928 this was a while ago, but i _THINK_ this bug was fixed. Feel free to reopen if you still hit it and i will investigate more.
